$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$ui = Get-Content -LiteralPath (Join-Path $root 'AgentUi.cs') -Encoding UTF8 -Raw
$history = Get-Content -LiteralPath (Join-Path $root 'StateHistory.cs') -Encoding UTF8 -Raw
$theme = Get-Content -LiteralPath (Join-Path $root 'PixelTheme.cs') -Encoding UTF8 -Raw
$update = Get-Content -LiteralPath (Join-Path $root 'UpdateService.cs') -Encoding UTF8 -Raw
$build = Get-Content -LiteralPath (Join-Path $root 'build.ps1') -Encoding UTF8 -Raw
$readme = Get-Content -LiteralPath (Join-Path $root 'README.md') -Encoding UTF8 -Raw
$logoGenerator = Get-Content -LiteralPath (Join-Path $root 'tools\generate_pixel_logo.py') -Encoding UTF8 -Raw
$dpi = Get-Content -LiteralPath (Join-Path $root 'DpiSupport.cs') -Encoding UTF8 -Raw
$stats = Get-Content -LiteralPath (Join-Path $root 'UsageStatistics.cs') -Encoding UTF8 -Raw
$taskCenter = Get-Content -LiteralPath (Join-Path $root 'TaskCenter.cs') -Encoding UTF8 -Raw
$installer = Get-Content -LiteralPath (Join-Path $root 'InstallerStub.cs') -Encoding UTF8 -Raw
$all = @('AgentTrafficLight.cs','AgentUi.cs','StateHistory.cs','TaskCenter.cs','UpdateService.cs','PixelTheme.cs','DpiSupport.cs','UsageStatistics.cs','InstallerStub.cs') | ForEach-Object { Get-Content -LiteralPath (Join-Path $root $_) -Encoding UTF8 -Raw }

if (($all -join "`n") -match 'MessageBox\.Show') { throw 'A native MessageBox remains and breaks the unified pixel style.' }
if ($ui -notmatch 'BackColor = PixelTheme\.Paper' -or $ui -notmatch 'PixelTheme\.PaintWindow') { throw 'Settings page is not using the white pixel theme.' }
if ($ui -notmatch 'ClientSize = new Size\(760, 438\)' -or $ui -match '仅统计状态时长与完成数量，不保存聊天正文' -or $ui -match 'PixelTheme\.Label\(') { throw 'Settings page still contains redundant explanatory labels or excess height.' }
if ($ui -notmatch 'AGENT BEACON v" \+ AppInfo\.Version \+ " // 设置' -or $ui -notmatch '今日统计' -or $ui -notmatch 'UsageStatistics\.Duration' -or $ui -notmatch '检查 / 修复') { throw 'Settings page does not show the current version, daily statistics, and integration repair entry.' }
if ($ui -notmatch '复制 TRAE MCP.+Size = new Size\(188, 32\)' -or $ui -notmatch '检查 / 修复集成.+Location = new Point\(22, 350\)' -or $ui -notmatch '状态中心.+Location = new Point\(220, 350\)') { throw 'Settings integrations are not using the compact two-column layout.' }
if ($ui -notmatch 'sealed class NotificationSettingsForm' -or $ui -notmatch '黄灯通知延迟' -or $ui -notmatch '长任务提醒') { throw 'Pixel notification policy page is missing.' }
if ($history -notmatch 'ClientSize = new Size\(760, 438\)' -or $history -notmatch 'overviewPage\.Location = new Point\(6, 46\)' -or $history -notmatch 'ShowOverview\(\)' -or $history -notmatch 'ShowMore\(\)' -or $history -notmatch 'Text = "更多"' -or $history -notmatch 'Text = "返回"' -or $history -notmatch 'FormBorderStyle = FormBorderStyle\.None' -or $history -notmatch 'MaximizeBox = false; MinimizeBox = false') { throw 'Compact bordered status center overview/more navigation is missing.' }
if ($history -notmatch 'Text = "清除"' -or $history -notmatch 'Text = "清除全部"' -or $history -notmatch 'TaskCenterState\.Dismiss\(task\)' -or $history -notmatch 'TaskCenterState\.DismissAll\(waiting\)' -or $history -notmatch 'Math\.Min\(3, waiting\.Count\)' -or $history -notmatch 'Math\.Min\(running\.Count, Math\.Min\(3,' -or $history -notmatch 'RenderAtomically\(overviewPage' -or $history -notmatch 'if \(reloading' -or $taskCenter -notmatch 'TaskDismissalStore' -or $taskCenter -notmatch 'SuppressSupersededStaleSessions' -or $history -notmatch '同一会话有新的 MCP 或 Agent 事件时会自动恢复监控') { throw 'Status center does not provide complete stale-wait cleanup, bounded row rendering, flicker-free refresh, or stale Codex session retirement.' }
if ($taskCenter -notmatch 'sealed class TaskQueuePopup' -or $taskCenter -notmatch 'Math\.Min\(438, height\)' -or $taskCenter -notmatch 'MouseDown \+= BeginDrag' -or $taskCenter -notmatch 'renderedSignature' -or $taskCenter -notmatch 'IsTransient' -or $ui -notmatch 'widget\.CenterClicked \+= delegate \{ ShowFullStatusCenter\(\); \}' -or $ui -notmatch 'widget\.SettingsClicked' -or $ui -notmatch 'Math\.Round\(88 \* scale\)' -or $ui -match '等待.+运行.+计数牌') { throw 'Compact direct status-center pole entry, original pole height, or stable task queue is missing.' }
if ($taskCenter -notmatch 'PendingTaskStore' -or $taskCenter -notmatch 'StalledAfterMs' -or $taskCenter -notmatch '超过 10 分钟无进展' -or $taskCenter -notmatch 'safe\.Title = safe\.Source \+ " 任务"; safe\.Cwd = ""') { throw 'Restart recovery, stuck detection or privacy-safe task snapshot is incomplete.' }
if ($history -notmatch 'DiagnosticsHub\.Report\(\)' -or $ui -match 'DiagnosticsHub\.Report\(\)') { throw 'Live diagnostics were not moved into the status center.' }
if ($theme -notmatch 'sealed class PixelDialog' -or $theme -notmatch 'Paper = Color\.FromArgb\(255, 255, 255\)' -or $theme -notmatch 'FillRectangle\(ink, 0, 0, width, 6\)') { throw 'Heavy white pixel dialog theme is incomplete.' }
if ($theme -notmatch 'sealed class PixelMenuRenderer' -or $ui -notmatch 'PixelTheme\.StyleMenu\(trayMenu\)' -or $ui -notmatch 'PixelTheme\.StyleMenu\(taskbarMenu\)' -or $ui -notmatch 'widget\.ContextMenuStrip = trayMenu') { throw 'Tray menus do not use the pixel renderer.' }
if ($theme -notmatch 'item\.AutoSize = false' -or $theme -notmatch 'item\.Size = new Size\(136, 29\)' -or $theme -notmatch 'Rectangle area = new Rectangle\(2, 1, e\.Item\.Width - 4, e\.Item\.Height - 2\)') { throw 'Pixel menu width and selected background are not compact and aligned.' }
if ($ui -notmatch 'spacious' -and $theme -notmatch 'spacious') { throw 'Pixel dialogs do not support a compact layout.' }
$ownedUi = $ui + $history + $theme
if ($ownedUi -match 'Microsoft YaHei UI|Consolas' -or $theme -notmatch 'FontName = "SimSun"' -or $theme -notmatch 'MonoFontName = "NSimSun"') { throw 'App-owned UI does not use the unified CJK pixel font family.' }
if ($dpi -notmatch 'SetProcessDpiAwarenessContext' -or $dpi -notmatch 'Screen\.FromRectangle' -or $ui -notmatch 'SystemEvents\.DisplaySettingsChanged' -or ($all -join "`n") -notmatch 'AutoScaleMode = AutoScaleMode\.Dpi') { throw 'Per-monitor DPI and multi-display protection are incomplete.' }
if ($stats -notmatch 'AnonymousKey' -or $stats -match 'Title|Detail|Evidence') { throw 'Usage statistics are not privacy-safe.' }
if ($theme -notmatch 'TextAlign = ContentAlignment\.MiddleCenter' -or $ui -notmatch 'TextAlign = ContentAlignment\.MiddleCenter') { throw 'Centerable UI text is not centered.' }
if ($theme -notmatch 'sealed class PixelProgressForm' -or $theme -notmatch 'sealed class PixelProgressBar' -or $ui -notmatch 'UpdateService\.Download\(info, progress\.Report\)' -or $update -notmatch 'Action<int, string> report') { throw 'Automatic update does not use the pixel progress UI with real progress callbacks.' }
if ($history -match 'ScrollBars\.Vertical' -or $history -notmatch 'sealed class PixelScrollBar' -or $history -notmatch 'sealed class PixelLogBox' -or $history -notmatch 'EM_LINESCROLL') { throw 'Status center still uses native scrollbars instead of the functional pixel scrollbar.' }
if ($theme -notmatch 'AppIcon = LoadAppIcon\(\)' -or $theme -notmatch 'Icon\.ExtractAssociatedIcon\(Application\.ExecutablePath\)' -or ([regex]::Matches($ownedUi, 'Icon = PixelTheme\.AppIcon')).Count -lt 5) { throw 'App-owned windows are not consistently using the embedded application icon.' }
if ($build -notmatch 'assets\\Agent-Beacon\.ico' -or $build -notmatch 'Agent-Beacon-Setup-\$version\.exe' -or $build -notmatch 'Agent-Beacon-Portable-\$version\.zip' -or $readme -notmatch 'assets/Agent-Beacon\.png' -or $logoGenerator -notmatch 'Image\.Resampling\.NEAREST' -or $logoGenerator -notmatch 'SIZES = \(16, 20, 24, 32, 40, 48, 64, 128, 256\)') { throw 'Pixel logo and portable/installer packages are not consistently generated.' }
if ($installer -notmatch '安装位置（支持自定义）' -or $installer -notmatch 'new FolderBrowserDialog' -or $installer -notmatch 'NormalizeInstallDirectory' -or $installer -notmatch 'Program\.Install\(autoStart\.Checked, installPath\.Text\)') { throw 'Installer does not support a validated custom installation directory.' }
Write-Host 'PASS unified pixel fonts, centered text, pixel logo/window icons, fixed status center, pixel dialogs/menus and update progress'
